version: "3"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://wiki.adtya.xyz
      DB_HOST: bookstack_db
      DB_USER: bookstack
      FILE__DB_PASS: /run/secrets/db_password
      DB_DATABASE: bookstackdb
    volumes:
      - app_data:/config
    ports:
      - 3002:80
    depends_on:
      - bookstack_db
    secrets:
      - db_password

  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      TZ: Europe/London
      MYSQL_DATABASE: bookstackdb
      MYSQL_USER: bookstack
      FILE__MYSQL_PASSWORD: /run/secrets/db_password
    volumes:
      - db_data:/config
    secrets:
      - db_password
      - db_root_password

secrets:
  db_password:
    file: .db_password
  db_root_password:
    file: .db_root_password

volumes:
  app_data:
  db_data:
