version: "3"

services:
  bookstack_web:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack_web
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kolkata
      FILE__APP_URL: /run/secrets/app_url
      DB_HOST: bookstack_db
      DB_USER: bookstack
      DB_DATABASE: bookstackdb
      FILE__DB_PASS: /run/secrets/db_password
    volumes:
      - app_data:/config
    ports:
      - 3002:80
    depends_on:
      - bookstack_db
    secrets:
      - db_password
      - app_url

  bookstack_db:
    image: mariadb:10
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookstackdb
      MYSQL_USER: bookstack
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password

secrets:
  db_password:
    file: .db_password
  app_url:
    file: .app_url

volumes:
  app_data:
  db_data:

