version: "3"

services:
  portainer_server:
    image: portainer/portainer-ce:latest
    container_name: portainer_server
    restart: unless-stopped
    env_file: .env
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

volumes:
  data:
