version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "3000:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      VIRTUAL_HOST: 'pihole.local'
      WEBPASSWORD_FILE: /run/secrets/web_password
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq-d:/etc/dnsmasq.d/
    secrets:
      - web_password
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq-d:

secrets:
  web_password:
    file: .web_password
