version: "3"

services:
  nextcloud:
      image: nextcloud:stable
      restart: unless-stopped
      environment:
        - POSTGRES_HOST: nextcloud_db
        - POSTGRES_USER: nextcloud
        - POSTGRES_DB: nextcloud_user
        - POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      secrets:
        - db_password
      volumes:
        - /mnt/storage/cloud:/var/www/html

  nextcloud_db:
    image: postgres:13.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

secrets:
  db_password:
    file: .db_password
