version: "3"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - config:/config
      - /mnt/data/cloud:/data
    ports:
      - 443:443
    restart: unless-stopped

volumes:
  config:

