version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 127.0.0.1:3001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: someuser
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wp_content:/var/www/html
    depends_on:
      - db
    secrets:
      - db_password

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: someuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password

volumes:
  wp_content:
  db_data:

secrets:
  db_password:
    file: .db_password
