version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - upload:/var/www/html/storage/upload
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SITE_OWNER_FILE=/run/secrets/site_owner
      - APP_KEY_FILE=/run/secrets/app_key
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=en_US
      - TZ=Asia/Kolkata
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack
      - APP_LOG_LEVEL=notice
      - AUDIT_LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - 3003:8080
    secrets:
      - db_password
      - site_owner
      - app_key
    depends_on:
      - db
  db:
    image: mariadb:10
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=firefly
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_password

volumes:
   upload:
   db:

secrets:
  db_password:
    file: .db_password
  site_owner:
    file: .site_owner
  app_key:
    file: .app_key
