version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - duin_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Kolkata
      LOG_LEVEL: info
      LOG_JSON: false
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_PROVIDERS_DOCKER: true
    labels:
      - "diun.enable=true"
    restart: unless-stopped

volumes:
  duin_data:
