version: "3"

services:
  wikijs:
    image: requarks/wiki:2
    restart: unless-stopped
    user: 1000:1000
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikiuser
      DB_PASS_FILE: /run/secrets/db_password
      DB_NAME: wikijs
    ports:
      - 127.0.0.1:3002:3000
    secrets:
      - db_password
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true

  db:
    image: postgres:13.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

secrets:
  db_password:
    file: .db_password
